version: '3.3'


services:

  rabbitmq:
    image: rabbitmq:3.9.26-management-alpine
    env_file:
      - .env
    ports:
      - "15672:15672"

  db:
    image: postgres:13-bullseye
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env
    depends_on:
      - rabbitmq

  web:
    image: krivse/backend_appeals:v2.0
#    image: krivse/backend_appeals:v1.0 (debian)
#    build:
#      context: backend
#      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./frontend/static:/app/static/
      - ./frontend/templates:/app/templates/
    env_file:
      - .env
    depends_on:
      - rabbitmq

  frontend:
    image: nginx:1.19.3
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./frontend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/static/:/usr/share/nginx/html/static/
      - ./frontend/templates/:/usr/share/nginx/html/templates/
    depends_on:
      - web

  servicedb:
    image: krivse/consumer_appeals:v2.0
#    image: krivse/comsumer_appeals:v1.0 (debian)
#    build:
#      context: servicedb
#      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - web

volumes:
  db_data: